name: flutter_translation_sheet
description: Flutter Translation Sheet (fts) is a simple tool to help you with
  localization (l10n) generating json, arb and dart files.
version: 1.0.34
maintainer: Rodrigo LÃ³pez (@roipeker)
homepage: https://github.com/roipeker/flutter_translation_sheet
repository: https://github.com/roipeker/flutter_translation_sheet/
issue_tracker: https://github.com/roipeker/flutter_translation_sheet/issues

executables:
  fts: main

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  dcli: ^8.4.2
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  io: ^1.0.4
  http: ^1.2.0
  path: ^1.9.0
  recase: ^4.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0